name: SignEditFix
version: @project.version@
main: uk.co.notnull.signeditfix.SignEditFix
api-version: 1.16
author: Jim (NotKatuen)
description: Fix Worldguard failing to block Purpur sign editing
depend: [ WorldGuard, WorldEdit ]
